include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "unused/**"
    - "scripts/**"
    - "packages/xterm/example/**"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_void_async: true
    unawaited_futures: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    throw_in_finally: true
    use_build_context_synchronously: true
    sort_pub_dependencies: true
    require_trailing_commas: true
    use_super_parameters: true
    prefer_const_constructors_in_immutables: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    test_types_in_equals: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    valid_regexps: true
