import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:crypto/crypto.dart';

/// Auto SSH Key Management System
/// 
/// Provides comprehensive SSH key management with automatic generation,
/// rotation, secure storage, and key lifecycle management
class AutoSSHKeyManagement {
  final Map<String, SSHKey> _keys = {};
  final Map<String, KeyMetadata> _keyMetadata = {};
  final List<KeyRotationPolicy> _rotationPolicies = [];
  Timer? _rotationTimer;
  String? _storagePath;
  
  static const Duration _rotationCheckInterval = Duration(hours: 6);
  static const Duration _defaultKeyLifetime = Duration(days: 90);
  static const int _defaultKeySize = 4096;
  
  /// Initialize SSH key management system
  Future<void> initialize() async {
    try {
      // Get storage path for keys
      final directory = await getApplicationDocumentsDirectory();
      _storagePath = '${directory.path}/ssh_keys';
      
      // Create directory if it doesn't exist
      await Directory(_storagePath!).create(recursive: true);
      
      // Load existing keys
      await _loadKeys();
      
      // Setup default rotation policies
      _setupDefaultPolicies();
      
      // Start rotation monitoring
      _rotationTimer = Timer.periodic(_rotationCheckInterval, (_) => _checkKeyRotations());
      
      debugPrint('🔑 Auto SSH Key Management initialized');
    } catch (e) {
      debugPrint('❌ Failed to initialize SSH Key Management: $e');
      rethrow;
    }
  }
  
  /// Generate new SSH key pair
  Future<KeyResult> generateKeyPair({
    required String keyName,
    KeyType keyType = KeyType.rsa,
    int keySize = 4096,
    String? comment,
    Map<String, String>? metadata,
    KeyRotationPolicy? rotationPolicy,
  }) async {
    try {
      // Check if key already exists
      if (_keys.containsKey(keyName)) {
        return KeyResult(
          success: false,
          error: 'Key with name $keyName already exists',
        );
      }
      
      // Generate key pair
      final keyPair = await _generateKeyPair(keyType, keySize);
      if (keyPair == null) {
        return KeyResult(
          success: false,
          error: 'Failed to generate key pair',
        );
      }
      
      // Create SSH key object
      final sshKey = SSHKey(
        name: keyName,
        type: keyType,
        size: keySize,
        publicKey: keyPair.publicKey,
        privateKey: keyPair.privateKey,
        fingerprint: keyPair.fingerprint,
        comment: comment ?? 'Generated by Termisol',
        createdAt: DateTime.now(),
        lastRotated: DateTime.now(),
      );
      
      // Create metadata
      final keyMeta = KeyMetadata(
        keyName: keyName,
        keyType: keyType,
        keySize: keySize,
        algorithm: keyType.name.toUpperCase(),
        createdAt: DateTime.now(),
        expiresAt: DateTime.now().add(_defaultKeyLifetime),
        lastRotated: DateTime.now(),
        rotationPolicy: rotationPolicy ?? _getDefaultRotationPolicy(keyType),
        usageCount: 0,
        lastUsed: null,
        metadata: metadata ?? {},
      );
      
      // Store key and metadata
      _keys[keyName] = sshKey;
      _keyMetadata[keyName] = keyMeta;
      
      // Save to disk
      await _saveKey(sshKey);
      await _saveKeyMetadata(keyMeta);
      
      debugPrint('🔑 Generated SSH key pair: $keyName (${keyType.name.toUpperCase()}-$keySize)');
      
      return KeyResult(
        success: true,
        keyName: keyName,
        publicKey: sshKey.publicKey,
        fingerprint: sshKey.fingerprint,
      );
    } catch (e) {
      debugPrint('❌ Failed to generate key pair: $e');
      return KeyResult(
        success: false,
        error: e.toString(),
      );
    }
  }
  
  /// Import existing SSH key
  Future<KeyResult> importKey({
    required String keyName,
    required String privateKey,
    String? publicKey,
    String? comment,
    KeyType? keyType,
    Map<String, String>? metadata,
  }) async {
    try {
      // Check if key already exists
      if (_keys.containsKey(keyName)) {
        return KeyResult(
          success: false,
          error: 'Key with name $keyName already exists',
        );
      }
      
      // Parse key to determine type and extract public key if needed
      final parsedKey = await _parsePrivateKey(privateKey, keyType);
      if (parsedKey == null) {
        return KeyResult(
          success: false,
          error: 'Failed to parse private key',
        );
      }
      
      // Generate fingerprint
      final fingerprint = _generateFingerprint(parsedKey.publicKey);
      
      // Create SSH key object
      final sshKey = SSHKey(
        name: keyName,
        type: parsedKey.type,
        size: parsedKey.size,
        publicKey: publicKey ?? parsedKey.publicKey,
        privateKey: privateKey,
        fingerprint: fingerprint,
        comment: comment ?? 'Imported key',
        createdAt: DateTime.now(),
        lastRotated: DateTime.now(),
      );
      
      // Create metadata
      final keyMeta = KeyMetadata(
        keyName: keyName,
        keyType: parsedKey.type,
        keySize: parsedKey.size,
        algorithm: parsedKey.type.name.toUpperCase(),
        createdAt: DateTime.now(),
        expiresAt: DateTime.now().add(_defaultKeyLifetime),
        lastRotated: DateTime.now(),
        rotationPolicy: _getDefaultRotationPolicy(parsedKey.type),
        usageCount: 0,
        lastUsed: null,
        metadata: metadata ?? {},
      );
      
      // Store key and metadata
      _keys[keyName] = sshKey;
      _keyMetadata[keyName] = keyMeta;
      
      // Save to disk
      await _saveKey(sshKey);
      await _saveKeyMetadata(keyMeta);
      
      debugPrint('🔑 Imported SSH key: $keyName');
      
      return KeyResult(
        success: true,
        keyName: keyName,
        publicKey: sshKey.publicKey,
        fingerprint: sshKey.fingerprint,
      );
    } catch (e) {
      debugPrint('❌ Failed to import key: $e');
      return KeyResult(
        success: false,
        error: e.toString(),
      );
    }
  }
  
  /// Delete SSH key
  Future<bool> deleteKey(String keyName) async {
    try {
      final key = _keys[keyName];
      if (key == null) return false;
      
      // Remove from memory
      _keys.remove(keyName);
      _keyMetadata.remove(keyName);
      
      // Delete files
      final privateKeyFile = File('$_storagePath/$keyName');
      final publicKeyFile = File('$_storagePath/$keyName.pub');
      final metadataFile = File('$_storagePath/$keyName.meta');
      
      await Future.wait([
        if (await privateKeyFile.exists()) privateKeyFile.delete(),
        if (await publicKeyFile.exists()) publicKeyFile.delete(),
        if (await metadataFile.exists()) metadataFile.delete(),
      ]);
      
      debugPrint('🔑 Deleted SSH key: $keyName');
      return true;
    } catch (e) {
      debugPrint('❌ Failed to delete key $keyName: $e');
      return false;
    }
  }
  
  /// Rotate SSH key
  Future<KeyResult> rotateKey(String keyName) async {
    try {
      final oldKey = _keys[keyName];
      final oldMetadata = _keyMetadata[keyName];
      
      if (oldKey == null || oldMetadata == null) {
        return KeyResult(
          success: false,
          error: 'Key not found: $keyName',
        );
      }
      
      // Generate new key with same parameters
      final newKeyResult = await generateKeyPair(
        keyName: '${keyName}_rotated_${DateTime.now().millisecondsSinceEpoch}',
        keyType: oldKey.type,
        keySize: oldKey.size,
        comment: 'Rotated from $keyName',
        metadata: Map.from(oldMetadata.metadata),
        rotationPolicy: oldMetadata.rotationPolicy,
      );
      
      if (!newKeyResult.success) {
        return newKeyResult;
      }
      
      // Backup old key
      await _backupKey(oldKey);
      
      // Update metadata for old key
      oldMetadata.isDeprecated = true;
      oldMetadata.deprecatedAt = DateTime.now();
      oldMetadata.replacedBy = newKeyResult.keyName;
      await _saveKeyMetadata(oldMetadata);
      
      debugPrint('🔑 Rotated SSH key: $keyName -> ${newKeyResult.keyName}');
      
      return newKeyResult;
    } catch (e) {
      debugPrint('❌ Failed to rotate key $keyName: $e');
      return KeyResult(
        success: false,
        error: e.toString(),
      );
    }
  }
  
  /// Get SSH key
  SSHKey? getKey(String keyName) {
    return _keys[keyName];
  }
  
  /// Get key metadata
  KeyMetadata? getKeyMetadata(String keyName) {
    return _keyMetadata[keyName];
  }
  
  /// Get all keys
  List<SSHKey> getAllKeys() {
    return _keys.values.toList();
  }
  
  /// Get active keys (not deprecated)
  List<SSHKey> getActiveKeys() {
    return _keys.values.where((key) {
      final metadata = _keyMetadata[key.name];
      return metadata != null && !metadata.isDeprecated;
    }).toList();
  }
  
  /// Get keys that need rotation
  List<String> getKeysNeedingRotation() {
    final now = DateTime.now();
    final keysNeedingRotation = <String>[];
    
    for (final entry in _keyMetadata.entries) {
      final metadata = entry.value;
      
      if (metadata.isDeprecated) continue;
      
      // Check if key is expired
      if (now.isAfter(metadata.expiresAt)) {
        keysNeedingRotation.add(entry.key);
        continue;
      }
      
      // Check rotation policy
      final policy = metadata.rotationPolicy;
      if (policy.autoRotate && now.difference(metadata.lastRotated) > policy.rotationInterval) {
        keysNeedingRotation.add(entry.key);
      }
    }
    
    return keysNeedingRotation;
  }
  
  /// Record key usage
  void recordKeyUsage(String keyName) {
    final metadata = _keyMetadata[keyName];
    if (metadata != null) {
      metadata.usageCount++;
      metadata.lastUsed = DateTime.now();
      _saveKeyMetadata(metadata);
    }
  }
  
  /// Add rotation policy
  void addRotationPolicy(KeyRotationPolicy policy) {
    _rotationPolicies.add(policy);
    debugPrint('🔑 Added rotation policy: ${policy.name}');
  }
  
  /// Export public key
  String? exportPublicKey(String keyName) {
    final key = _keys[keyName];
    return key?.publicKey;
  }
  
  /// Validate key format
  Future<bool> validateKeyFormat(String keyName) async {
    try {
      final key = _keys[keyName];
      if (key == null) return false;
      
      // Validate private key format
      final isValid = await _validatePrivateKeyFormat(key.privateKey, key.type);
      return isValid;
    } catch (e) {
      debugPrint('❌ Failed to validate key format for $keyName: $e');
      return false;
    }
  }
  
  /// Generate key pair
  Future<KeyPair?> _generateKeyPair(KeyType keyType, int keySize) async {
    try {
      // Simulate key generation
      await Future.delayed(Duration(milliseconds: 1000));
      
      // Generate mock key pair
      final random = Random.secure();
      final publicKeyBytes = List<int>.generate(keySize ~/ 8, (_) => random.nextInt(256));
      final privateKeyBytes = List<int>.generate(keySize ~/ 8, (_) => random.nextInt(256));
      
      final publicKey = _formatPublicKey(publicKeyBytes, keyType);
      final privateKey = _formatPrivateKey(privateKeyBytes, keyType);
      final fingerprint = _generateFingerprint(publicKey);
      
      return KeyPair(
        publicKey: publicKey,
        privateKey: privateKey,
        fingerprint: fingerprint,
        type: keyType,
        size: keySize,
      );
    } catch (e) {
      debugPrint('❌ Failed to generate key pair: $e');
      return null;
    }
  }
  
  /// Parse private key
  Future<ParsedKey?> _parsePrivateKey(String privateKey, KeyType? keyType) async {
    try {
      // Simulate key parsing
      await Future.delayed(Duration(milliseconds: 200));
      
      // Extract public key from private key
      final publicKey = _extractPublicKeyFromPrivate(privateKey);
      
      return ParsedKey(
        type: keyType ?? KeyType.rsa,
        size: _defaultKeySize,
        publicKey: publicKey,
      );
    } catch (e) {
      debugPrint('❌ Failed to parse private key: $e');
      return null;
    }
  }
  
  /// Format public key
  String _formatPublicKey(List<int> bytes, KeyType keyType) {
    final base64Key = base64.encode(bytes);
    final algorithm = keyType.name.toUpperCase();
    return '$algorithm $base64Key termisol-key';
  }
  
  /// Format private key
  String _formatPrivateKey(List<int> bytes, KeyType keyType) {
    final base64Key = base64.encode(bytes);
    return '''
-----BEGIN ${keyType.name.toUpperCase()} PRIVATE KEY-----
$base64Key
-----END ${keyType.name.toUpperCase()} PRIVATE KEY-----
''';
  }
  
  /// Extract public key from private key
  String _extractPublicKeyFromPrivate(String privateKey) {
    // Simulate extracting public key
    final random = Random.secure();
    final publicKeyBytes = List<int>.generate(256, (_) => random.nextInt(256));
    final base64Key = base64.encode(publicKeyBytes);
    return 'RSA $base64Key extracted-key';
  }
  
  /// Generate fingerprint
  String _generateFingerprint(String publicKey) {
    final bytes = utf8.encode(publicKey);
    final digest = sha256.convert(bytes);
    return 'SHA256:${base64.encode(digest.bytes).replaceAll(RegExp(r'[^a-zA-Z0-9+/]'), '').substring(0, 43)}';
  }
  
  /// Validate private key format
  Future<bool> _validatePrivateKeyFormat(String privateKey, KeyType keyType) async {
    try {
      // Simulate validation
      await Future.delayed(Duration(milliseconds: 100));
      
      // Check if it has proper PEM headers
      final expectedHeader = '-----BEGIN ${keyType.name.toUpperCase()} PRIVATE KEY-----';
      final expectedFooter = '-----END ${keyType.name.toUpperCase()} PRIVATE KEY-----';
      
      return privateKey.contains(expectedHeader) && privateKey.contains(expectedFooter);
    } catch (e) {
      return false;
    }
  }
  
  /// Setup default rotation policies
  void _setupDefaultPolicies() {
    _rotationPolicies.addAll([
      KeyRotationPolicy(
        name: 'Standard RSA',
        keyType: KeyType.rsa,
        rotationInterval: Duration(days: 90),
        autoRotate: true,
        warnBeforeRotation: Duration(days: 7),
      ),
      KeyRotationPolicy(
        name: 'Standard Ed25519',
        keyType: KeyType.ed25519,
        rotationInterval: Duration(days: 180),
        autoRotate: true,
        warnBeforeRotation: Duration(days: 14),
      ),
      KeyRotationPolicy(
        name: 'High Security',
        keyType: KeyType.rsa,
        rotationInterval: Duration(days: 30),
        autoRotate: true,
        warnBeforeRotation: Duration(days: 3),
      ),
    ]);
  }
  
  /// Get default rotation policy for key type
  KeyRotationPolicy _getDefaultRotationPolicy(KeyType keyType) {
    return _rotationPolicies.firstWhere(
      (policy) => policy.keyType == keyType,
      orElse: () => KeyRotationPolicy(
        name: 'Default',
        keyType: keyType,
        rotationInterval: _defaultKeyLifetime,
        autoRotate: false,
      ),
    );
  }
  
  /// Load keys from storage
  Future<void> _loadKeys() async {
    try {
      if (_storagePath == null) return;
      
      final directory = Directory(_storagePath!);
      if (!await directory.exists()) return;
      
      await for (final entity in directory.list()) {
        if (entity is File && entity.path.endsWith('.meta')) {
          try {
            final content = await entity.readAsString();
            final data = json.decode(content) as Map<String, dynamic>;
            
            final metadata = KeyMetadata.fromJson(data);
            _keyMetadata[metadata.keyName] = metadata;
            
            // Load the actual key
            await _loadKey(metadata.keyName);
          } catch (e) {
            debugPrint('❌ Failed to load key metadata from ${entity.path}: $e');
          }
        }
      }
      
      debugPrint('📂 Loaded ${_keys.length} SSH keys from disk');
    } catch (e) {
      debugPrint('❌ Failed to load keys: $e');
    }
  }
  
  /// Load individual key
  Future<void> _loadKey(String keyName) async {
    try {
      final privateKeyFile = File('$_storagePath/$keyName');
      final publicKeyFile = File('$_storagePath/$keyName.pub');
      
      if (!await privateKeyFile.exists()) return;
      
      final privateKey = await privateKeyFile.readAsString();
      final publicKey = await publicKeyFile.exists() ? await publicKeyFile.readAsString() : '';
      
      final metadata = _keyMetadata[keyName];
      if (metadata == null) return;
      
      final sshKey = SSHKey(
        name: keyName,
        type: metadata.keyType,
        size: metadata.keySize,
        publicKey: publicKey,
        privateKey: privateKey,
        fingerprint: '', // Would be calculated
        comment: 'Loaded from storage',
        createdAt: metadata.createdAt,
        lastRotated: metadata.lastRotated,
      );
      
      _keys[keyName] = sshKey;
    } catch (e) {
      debugPrint('❌ Failed to load key $keyName: $e');
    }
  }
  
  /// Save key to disk
  Future<void> _saveKey(SSHKey key) async {
    try {
      final privateKeyFile = File('$_storagePath/${key.name}');
      final publicKeyFile = File('$_storagePath/${key.name}.pub');
      
      await privateKeyFile.writeAsString(key.privateKey);
      await publicKeyFile.writeAsString(key.publicKey);
      
      // Set file permissions (600 for private key, 644 for public key)
      await Process.run('chmod', ['600', privateKeyFile.path]);
      await Process.run('chmod', ['644', publicKeyFile.path]);
    } catch (e) {
      debugPrint('❌ Failed to save key ${key.name}: $e');
    }
  }
  
  /// Save key metadata
  Future<void> _saveKeyMetadata(KeyMetadata metadata) async {
    try {
      final metadataFile = File('$_storagePath/${metadata.keyName}.meta');
      await metadataFile.writeAsString(json.encode(metadata.toJson()));
    } catch (e) {
      debugPrint('❌ Failed to save metadata for ${metadata.keyName}: $e');
    }
  }
  
  /// Backup key
  Future<void> _backupKey(SSHKey key) async {
    try {
      final backupDir = Directory('$_storagePath/backups');
      await backupDir.create(recursive: true);
      
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final privateKeyFile = File('$_storagePath/${key.name}');
      final publicKeyFile = File('$_storagePath/${key.name}.pub');
      
      await privateKeyFile.copy('${backupDir.path}/${key.name}_$timestamp');
      await publicKeyFile.copy('${backupDir.path}/${key.name}.pub_$timestamp');
      
      debugPrint('🔑 Backed up key: ${key.name}');
    } catch (e) {
      debugPrint('❌ Failed to backup key ${key.name}: $e');
    }
  }
  
  /// Check key rotations
  Future<void> _checkKeyRotations() async {
    try {
      final keysNeedingRotation = getKeysNeedingRotation();
      
      for (final keyName in keysNeedingRotation) {
        final metadata = _keyMetadata[keyName];
        if (metadata == null) continue;
        
        if (metadata.rotationPolicy.autoRotate) {
          debugPrint('🔄 Auto-rotating key: $keyName');
          await rotateKey(keyName);
        } else {
          debugPrint('⚠️ Key needs rotation: $keyName');
        }
      }
    } catch (e) {
      debugPrint('❌ Failed to check key rotations: $e');
    }
  }
  
  /// Dispose SSH key management system
  Future<void> dispose() async {
    try {
      // Cancel rotation timer
      _rotationTimer?.cancel();
      
      // Clear sensitive data from memory
      _keys.clear();
      _keyMetadata.clear();
      
      debugPrint('🔑 Auto SSH Key Management disposed');
    } catch (e) {
      debugPrint('❌ Error during disposal: $e');
    }
  }
}

/// SSH key types
enum KeyType { rsa, dsa, ecdsa, ed25519 }

/// SSH key
class SSHKey {
  final String name;
  final KeyType type;
  final int size;
  final String publicKey;
  final String privateKey;
  final String fingerprint;
  final String comment;
  final DateTime createdAt;
  DateTime lastRotated;
  
  SSHKey({
    required this.name,
    required this.type,
    required this.size,
    required this.publicKey,
    required this.privateKey,
    required this.fingerprint,
    required this.comment,
    required this.createdAt,
    required this.lastRotated,
  });
}

/// Key metadata
class KeyMetadata {
  final String keyName;
  final KeyType keyType;
  final int keySize;
  final String algorithm;
  final DateTime createdAt;
  final DateTime expiresAt;
  DateTime lastRotated;
  final KeyRotationPolicy rotationPolicy;
  int usageCount;
  DateTime? lastUsed;
  bool isDeprecated;
  DateTime? deprecatedAt;
  String? replacedBy;
  final Map<String, String> metadata;
  
  KeyMetadata({
    required this.keyName,
    required this.keyType,
    required this.keySize,
    required this.algorithm,
    required this.createdAt,
    required this.expiresAt,
    required this.lastRotated,
    required this.rotationPolicy,
    this.usageCount = 0,
    this.lastUsed,
    this.isDeprecated = false,
    this.deprecatedAt,
    this.replacedBy,
    this.metadata = const {},
  });
  
  Map<String, dynamic> toJson() {
    return {
      'keyName': keyName,
      'keyType': keyType.name,
      'keySize': keySize,
      'algorithm': algorithm,
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt.toIso8601String(),
      'lastRotated': lastRotated.toIso8601String(),
      'rotationPolicy': rotationPolicy.name,
      'usageCount': usageCount,
      'lastUsed': lastUsed?.toIso8601String(),
      'isDeprecated': isDeprecated,
      'deprecatedAt': deprecatedAt?.toIso8601String(),
      'replacedBy': replacedBy,
      'metadata': metadata,
    };
  }
  
  factory KeyMetadata.fromJson(Map<String, dynamic> json) {
    return KeyMetadata(
      keyName: json['keyName'],
      keyType: KeyType.values.byName(json['keyType']),
      keySize: json['keySize'],
      algorithm: json['algorithm'],
      createdAt: DateTime.parse(json['createdAt']),
      expiresAt: DateTime.parse(json['expiresAt']),
      lastRotated: DateTime.parse(json['lastRotated']),
      rotationPolicy: KeyRotationPolicy(
        name: json['rotationPolicy'],
        keyType: KeyType.values.byName(json['keyType']),
        rotationInterval: Duration(days: 90), // Default
      ),
      usageCount: json['usageCount'] ?? 0,
      lastUsed: json['lastUsed'] != null ? DateTime.parse(json['lastUsed']) : null,
      isDeprecated: json['isDeprecated'] ?? false,
      deprecatedAt: json['deprecatedAt'] != null ? DateTime.parse(json['deprecatedAt']) : null,
      replacedBy: json['replacedBy'],
      metadata: Map<String, String>.from(json['metadata'] ?? {}),
    );
  }
}

/// Key rotation policy
class KeyRotationPolicy {
  final String name;
  final KeyType keyType;
  final Duration rotationInterval;
  final bool autoRotate;
  final Duration? warnBeforeRotation;
  final int? maxUsageCount;
  
  KeyRotationPolicy({
    required this.name,
    required this.keyType,
    required this.rotationInterval,
    this.autoRotate = false,
    this.warnBeforeRotation,
    this.maxUsageCount,
  });
}

/// Key pair
class KeyPair {
  final String publicKey;
  final String privateKey;
  final String fingerprint;
  final KeyType type;
  final int size;
  
  KeyPair({
    required this.publicKey,
    required this.privateKey,
    required this.fingerprint,
    required this.type,
    required this.size,
  });
}

/// Parsed key
class ParsedKey {
  final KeyType type;
  final int size;
  final String publicKey;
  
  ParsedKey({
    required this.type,
    required this.size,
    required this.publicKey,
  });
}

/// Key operation result
class KeyResult {
  final bool success;
  final String? keyName;
  final String? publicKey;
  final String? fingerprint;
  final String? error;
  
  KeyResult({
    required this.success,
    this.keyName,
    this.publicKey,
    this.fingerprint,
    this.error,
  });
}