import 'package:xterm/src/core/input/keys.dart';

/// see: https://doc.qt.io/qt-5/qt.html#key-enum
const qtKeynameMap = <String, TerminalKey>{
  'Escape': TerminalKey.escape,
  'Tab': TerminalKey.tab,
  'Backtab': TerminalKey.backtab,
  'Backspace': TerminalKey.backspace,
  'Return': TerminalKey.returnKey,
  'Enter': TerminalKey.enter,
  'NumEnter': TerminalKey.numpadEnter,
  'Insert': TerminalKey.insert,
  'Delete': TerminalKey.delete,
  'Pause': TerminalKey.pause,
  'Print': TerminalKey.print,
// 'sysreq': terminalkey.sysreq,
  'Clear': TerminalKey.numpadClear,
  'Home': TerminalKey.home,
  'End': TerminalKey.end,
  'Left': TerminalKey.arrowLeft,
  'Up': TerminalKey.arrowUp,
  'Right': TerminalKey.arrowRight,
  'Down': TerminalKey.arrowDown,
  'PageUp': TerminalKey.pageUp,
  'PageDown': TerminalKey.pageDown,
  'PgUp': TerminalKey.pageUp,
  'PgDown': TerminalKey.pageDown,
  'Shift': TerminalKey.shift,
  'Control': TerminalKey.control,
  'Meta': TerminalKey.meta,
  'Alt': TerminalKey.alt,
// 'altgr': terminalkey.altgr,
  'CapsLock': TerminalKey.capsLock,
  'NumLock': TerminalKey.numLock,
  'ScrollLock': TerminalKey.scrollLock,
  'F1': TerminalKey.f1,
  'F2': TerminalKey.f2,
  'F3': TerminalKey.f3,
  'F4': TerminalKey.f4,
  'F5': TerminalKey.f5,
  'F6': TerminalKey.f6,
  'F7': TerminalKey.f7,
  'F8': TerminalKey.f8,
  'F9': TerminalKey.f9,
  'F10': TerminalKey.f10,
  'F11': TerminalKey.f11,
  'F12': TerminalKey.f12,
  'F13': TerminalKey.f13,
  'F14': TerminalKey.f14,
  'F15': TerminalKey.f15,
  'F16': TerminalKey.f16,
  'F17': TerminalKey.f17,
  'F18': TerminalKey.f18,
  'F19': TerminalKey.f19,
  'F20': TerminalKey.f20,
  'F21': TerminalKey.f21,
  'F22': TerminalKey.f22,
  'F23': TerminalKey.f23,
  'F24': TerminalKey.f24,
// 'f25': terminalkey.f25,
// 'f26': terminalkey.f26,
// 'f27': terminalkey.f27,
// 'f28': terminalkey.f28,
// 'f29': terminalkey.f29,
// 'f30': terminalkey.f30,
// 'f31': terminalkey.f31,
// 'f32': terminalkey.f32,
// 'f33': terminalkey.f33,
// 'f34': terminalkey.f34,
// 'f35': terminalkey.f35,
// 'super_l': terminalkey.super_l,
// 'super_r': terminalkey.super_r,
// 'menu': terminalkey.menu,
// 'hyper_l': terminalkey.hyper_l,
// 'hyper_r': terminalkey.hyper_r,
  'Help': TerminalKey.help,
// 'direction_l': terminalkey.direction_l,
// 'direction_r': terminalkey.direction_r,
  'Space': TerminalKey.space,
  // 'Any': TerminalKey.any,
  // 'Exclam': TerminalKey.exclam,
  // 'QuoteDbl': TerminalKey.quoteDbl,
  // 'NumberSign': TerminalKey.numberSign,
  // 'Dollar': TerminalKey.dollar,
  // 'Percent': TerminalKey.percent,
  // 'Ampersand': TerminalKey.ampersand,
  // 'Apostrophe': TerminalKey.apostrophe,
  'ParenLeft': TerminalKey.numpadParenLeft,
  'ParenRight': TerminalKey.numpadParenRight,
  // 'Asterisk': TerminalKey.asterisk,
  // 'Plus': TerminalKey.plus,
  'Comma': TerminalKey.comma,
  'Minus': TerminalKey.minus,
  'Period': TerminalKey.period,
  'Slash': TerminalKey.slash,
  '0': TerminalKey.digit0,
  '1': TerminalKey.digit1,
  '2': TerminalKey.digit2,
  '3': TerminalKey.digit3,
  '4': TerminalKey.digit4,
  '5': TerminalKey.digit5,
  '6': TerminalKey.digit6,
  '7': TerminalKey.digit7,
  '8': TerminalKey.digit8,
  '9': TerminalKey.digit9,
// 'colon': terminalkey.colon,
  'Semicolon': TerminalKey.semicolon,
// 'less': terminalkey.less,
// 'equal': terminalkey.equal,
// 'greater': terminalkey.greater,
// 'question': terminalkey.question,
// 'at': terminalkey.at,
  'A': TerminalKey.keyA,
  'B': TerminalKey.keyB,
  'C': TerminalKey.keyC,
  'D': TerminalKey.keyD,
  'E': TerminalKey.keyE,
  'F': TerminalKey.keyF,
  'G': TerminalKey.keyG,
  'H': TerminalKey.keyH,
  'I': TerminalKey.keyI,
  'J': TerminalKey.keyJ,
  'K': TerminalKey.keyK,
  'L': TerminalKey.keyL,
  'M': TerminalKey.keyM,
  'N': TerminalKey.keyN,
  'O': TerminalKey.keyO,
  'P': TerminalKey.keyP,
  'Q': TerminalKey.keyQ,
  'R': TerminalKey.keyR,
  'S': TerminalKey.keyS,
  'T': TerminalKey.keyT,
  'U': TerminalKey.keyU,
  'V': TerminalKey.keyV,
  'W': TerminalKey.keyW,
  'X': TerminalKey.keyX,
  'Y': TerminalKey.keyY,
  'Z': TerminalKey.keyZ,
  'BracketLeft': TerminalKey.bracketLeft,
  'Backslash': TerminalKey.backslash,
  'BracketRight': TerminalKey.bracketRight,
// 'asciicircum': terminalkey.asciicircum,
  // 'Underscore': TerminalKey.underscore,
  // 'QuoteLeft': TerminalKey.quoteLeft,
// 'braceleft': terminalkey.braceleft,
  // 'Bar': TerminalKey.bar,
// 'braceright': terminalkey.braceright,
  // 'AsciiTilde': TerminalKey.asciiTilde,
// 'nobreakspace': terminalkey.nobreakspace,
// 'exclamdown': terminalkey.exclamdown,
// 'cent': terminalkey.cent,
// 'sterling': terminalkey.sterling,
// 'currency': terminalkey.currency,
// 'yen': terminalkey.yen,
// 'brokenbar': terminalkey.brokenbar,
// 'section': terminalkey.section,
// 'diaeresis': terminalkey.diaeresis,
// 'copyright': terminalkey.copyright,
// 'ordfeminine': terminalkey.ordfeminine,
// 'guillemotleft': terminalkey.guillemotleft,
// 'notsign': terminalkey.notsign,
// 'hyphen': terminalkey.hyphen,
// 'registered': terminalkey.registered,
// 'macron': terminalkey.macron,
// 'degree': terminalkey.degree,
// 'plusminus': terminalkey.plusminus,
// 'twosuperior': terminalkey.twosuperior,
// 'threesuperior': terminalkey.threesuperior,
// 'acute': terminalkey.acute,
// // 'mu': terminalkey.mu,
// 'paragraph': terminalkey.paragraph,
// 'periodcentered': terminalkey.periodcentered,
// 'cedilla': terminalkey.cedilla,
// 'onesuperior': terminalkey.onesuperior,
// 'masculine': terminalkey.masculine,
// 'guillemotright': terminalkey.guillemotright,
// 'onequarter': terminalkey.onequarter,
// 'onehalf': terminalkey.onehalf,
// 'threequarters': terminalkey.threequarters,
// 'questiondown': terminalkey.questiondown,
// 'agrave': terminalkey.agrave,
// 'aacute': terminalkey.aacute,
// 'acircumflex': terminalkey.acircumflex,
// 'atilde': terminalkey.atilde,
// 'adiaeresis': terminalkey.adiaeresis,
// 'aring': terminalkey.aring,
// 'ae': terminalkey.ae,
// 'ccedilla': terminalkey.ccedilla,
// 'egrave': terminalkey.egrave,
// 'eacute': terminalkey.eacute,
// 'ecircumflex': terminalkey.ecircumflex,
// 'ediaeresis': terminalkey.ediaeresis,
// 'igrave': terminalkey.igrave,
// 'iacute': terminalkey.iacute,
// 'icircumflex': terminalkey.icircumflex,
// 'idiaeresis': terminalkey.idiaeresis,
// 'eth': terminalkey.eth,
// 'ntilde': terminalkey.ntilde,
// 'ograve': terminalkey.ograve,
// 'oacute': terminalkey.oacute,
// 'ocircumflex': terminalkey.ocircumflex,
// 'otilde': terminalkey.otilde,
// 'odiaeresis': terminalkey.odiaeresis,
// 'multiply': terminalkey.multiply,
// 'ooblique': terminalkey.ooblique,
// 'ugrave': terminalkey.ugrave,
// 'uacute': terminalkey.uacute,
// 'ucircumflex': terminalkey.ucircumflex,
// 'udiaeresis': terminalkey.udiaeresis,
// 'yacute': terminalkey.yacute,
// 'thorn': terminalkey.thorn,
// 'ssharp': terminalkey.ssharp,
// 'division': terminalkey.division,
// 'ydiaeresis': terminalkey.ydiaeresis,
// 'multi_key': terminalkey.multi_key,
// 'codeinput': terminalkey.codeinput,
// 'singlecandidate': terminalkey.singlecandidate,
// 'multiplecandidate': terminalkey.multiplecandidate,
// 'previouscandidate': terminalkey.previouscandidate,
// 'mode_switch': terminalkey.mode_switch,
// 'kanji': terminalkey.kanji,
// 'muhenkan': terminalkey.muhenkan,
// 'henkan': terminalkey.henkan,
// 'romaji': terminalkey.romaji,
// 'hiragana': terminalkey.hiragana,
// 'katakana': terminalkey.katakana,
// 'hiragana_katakana': terminalkey.hiragana_katakana,
// 'zenkaku': terminalkey.zenkaku,
// 'hankaku': terminalkey.hankaku,
// 'zenkaku_hankaku': terminalkey.zenkaku_hankaku,
// 'touroku': terminalkey.touroku,
// 'massyo': terminalkey.massyo,
// 'kana_lock': terminalkey.kana_lock,
// 'kana_shift': terminalkey.kana_shift,
// 'eisu_shift': terminalkey.eisu_shift,
// 'eisu_toggle': terminalkey.eisu_toggle,
// 'hangul': terminalkey.hangul,
// 'hangul_start': terminalkey.hangul_start,
// 'hangul_end': terminalkey.hangul_end,
// 'hangul_hanja': terminalkey.hangul_hanja,
// 'hangul_jamo': terminalkey.hangul_jamo,
// 'hangul_romaja': terminalkey.hangul_romaja,
// 'hangul_jeonja': terminalkey.hangul_jeonja,
// 'hangul_banja': terminalkey.hangul_banja,
// 'hangul_prehanja': terminalkey.hangul_prehanja,
// 'hangul_posthanja': terminalkey.hangul_posthanja,
// 'hangul_special': terminalkey.hangul_special,
// 'dead_grave': terminalkey.dead_grave,
// 'dead_acute': terminalkey.dead_acute,
// 'dead_circumflex': terminalkey.dead_circumflex,
// 'dead_tilde': terminalkey.dead_tilde,
// 'dead_macron': terminalkey.dead_macron,
// 'dead_breve': terminalkey.dead_breve,
// 'dead_abovedot': terminalkey.dead_abovedot,
// 'dead_diaeresis': terminalkey.dead_diaeresis,
// 'dead_abovering': terminalkey.dead_abovering,
// 'dead_doubleacute': terminalkey.dead_doubleacute,
// 'dead_caron': terminalkey.dead_caron,
// 'dead_cedilla': terminalkey.dead_cedilla,
// 'dead_ogonek': terminalkey.dead_ogonek,
// 'dead_iota': terminalkey.dead_iota,
// 'dead_voiced_sound': terminalkey.dead_voiced_sound,
// 'dead_semivoiced_sound': terminalkey.dead_semivoiced_sound,
// 'dead_belowdot': terminalkey.dead_belowdot,
// 'dead_hook': terminalkey.dead_hook,
// 'dead_horn': terminalkey.dead_horn,
// 'dead_stroke': terminalkey.dead_stroke,
// 'dead_abovecomma': terminalkey.dead_abovecomma,
// 'dead_abovereversedcomma': terminalkey.dead_abovereversedcomma,
// 'dead_doublegrave': terminalkey.dead_doublegrave,
// 'dead_belowring': terminalkey.dead_belowring,
// 'dead_belowmacron': terminalkey.dead_belowmacron,
// 'dead_belowcircumflex': terminalkey.dead_belowcircumflex,
// 'dead_belowtilde': terminalkey.dead_belowtilde,
// 'dead_belowbreve': terminalkey.dead_belowbreve,
// 'dead_belowdiaeresis': terminalkey.dead_belowdiaeresis,
// 'dead_invertedbreve': terminalkey.dead_invertedbreve,
// 'dead_belowcomma': terminalkey.dead_belowcomma,
// 'dead_currency': terminalkey.dead_currency,
// 'dead_a': terminalkey.dead_a,
// 'dead_a': terminalkey.dead_a,
// 'dead_e': terminalkey.dead_e,
// 'dead_e': terminalkey.dead_e,
// 'dead_i': terminalkey.dead_i,
// 'dead_i': terminalkey.dead_i,
// 'dead_o': terminalkey.dead_o,
// 'dead_o': terminalkey.dead_o,
// 'dead_u': terminalkey.dead_u,
// 'dead_u': terminalkey.dead_u,
// 'dead_small_schwa': terminalkey.dead_small_schwa,
// 'dead_capital_schwa': terminalkey.dead_capital_schwa,
// 'dead_greek': terminalkey.dead_greek,
// 'dead_lowline': terminalkey.dead_lowline,
// 'dead_aboveverticalline': terminalkey.dead_aboveverticalline,
// 'dead_belowverticalline': terminalkey.dead_belowverticalline,
// 'dead_longsolidusoverlay': terminalkey.dead_longsolidusoverlay,
// 'back': terminalkey.back,
// 'forward': terminalkey.forward,
// 'stop': terminalkey.stop,
// 'refresh': terminalkey.refresh,
  'VolumeDown': TerminalKey.audioVolumeDown,
  'VolumeMute': TerminalKey.audioVolumeMute,
  'VolumeUp': TerminalKey.audioVolumeUp,
  'BassBoost': TerminalKey.bassBoost,
// 'bassup': terminalkey.bassup,
// 'bassdown': terminalkey.bassdown,
// 'trebleup': terminalkey.trebleup,
// 'trebledown': terminalkey.trebledown,
  'MediaPlay': TerminalKey.mediaPlay,
  'MediaStop': TerminalKey.mediaStop,
// 'mediaprevious': terminalkey.mediaprevious,
// 'medianext': terminalkey.medianext,
  'MediaRecord': TerminalKey.mediaRecord,
  'MediaPause': TerminalKey.mediaPause,
  'MediaTogglePlayPause': TerminalKey.mediaPlayPause,
  'HomePage': TerminalKey.browserHome,
// 'favorites': terminalkey.favorites,
// 'search': terminalkey.search,
// 'standby': terminalkey.standby,
// 'openurl': terminalkey.openurl,
// 'launchmail': terminalkey.launchmail,
// 'launchmedia': terminalkey.launchmedia,
// 'launch0': terminalkey.launch0,
// 'launch1': terminalkey.launch1,
// 'launch2': terminalkey.launch2,
// 'launch3': terminalkey.launch3,
// 'launch4': terminalkey.launch4,
// 'launch5': terminalkey.launch5,
// 'launch6': terminalkey.launch6,
// 'launch7': terminalkey.launch7,
// 'launch8': terminalkey.launch8,
// 'launch9': terminalkey.launch9,
// 'launcha': terminalkey.launcha,
// 'launchb': terminalkey.launchb,
// 'launchc': terminalkey.launchc,
// 'launchd': terminalkey.launchd,
// 'launche': terminalkey.launche,
// 'launchf': terminalkey.launchf,
// 'launchg': terminalkey.launchg,
// 'launchh': terminalkey.launchh,
  'MonBrightnessUp': TerminalKey.brightnessUp,
  'MonBrightnessDown': TerminalKey.brightnessDown,
// 'keyboardlightonoff': terminalkey.keyboardlightonoff,
// 'keyboardbrightnessup': terminalkey.keyboardbrightnessup,
// 'keyboardbrightnessdown': terminalkey.keyboardbrightnessdown,
  'PowerOff': TerminalKey.power,
  'WakeUp': TerminalKey.wakeUp,
  'Eject': TerminalKey.eject,
// 'screensaver': terminalkey.screensaver,
// 'www': terminalkey.www,
// 'memo': terminalkey.memo,
// 'lightbulb': terminalkey.lightbulb,
// 'shop': terminalkey.shop,
// 'history': terminalkey.history,
// 'addfavorite': terminalkey.addfavorite,
// 'hotlinks': terminalkey.hotlinks,
// 'brightnessadjust': terminalkey.brightnessadjust,
// 'finance': terminalkey.finance,
// 'community': terminalkey.community,
// 'audiorewind': terminalkey.audiorewind,
// 'backforward': terminalkey.backforward,
// 'applicationleft': terminalkey.applicationleft,
// 'applicationright': terminalkey.applicationright,
// 'book': terminalkey.book,
// 'cd': terminalkey.cd,
// 'calculator': terminalkey.calculator,
// 'todolist': terminalkey.todolist,
// 'cleargrab': terminalkey.cleargrab,
  'Close': TerminalKey.close,
  'Copy': TerminalKey.copy,
  'Cut': TerminalKey.cut,
// 'display': terminalkey.display,
// 'dos': terminalkey.dos,
// 'documents': terminalkey.documents,
// 'excel': terminalkey.excel,
// 'explorer': terminalkey.explorer,
// 'game': terminalkey.game,
// 'go': terminalkey.go,
// 'itouch': terminalkey.itouch,
// 'logoff': terminalkey.logoff,
// 'market': terminalkey.market,
// 'meeting': terminalkey.meeting,
// 'menukb': terminalkey.menukb,
// 'menupb': terminalkey.menupb,
// 'mysites': terminalkey.mysites,
// 'news': terminalkey.news,
// 'officehome': terminalkey.officehome,
// 'option': terminalkey.option,
// 'paste': terminalkey.paste,
// 'phone': terminalkey.phone,
// 'calendar': terminalkey.calendar,
// 'reply': terminalkey.reply,
// 'reload': terminalkey.reload,
// 'rotatewindows': terminalkey.rotatewindows,
// 'rotationpb': terminalkey.rotationpb,
// 'rotationkb': terminalkey.rotationkb,
  'Save': TerminalKey.save,
// 'send': terminalkey.send,
// 'spell': terminalkey.spell,
// 'splitscreen': terminalkey.splitscreen,
// 'support': terminalkey.support,
// 'taskpane': terminalkey.taskpane,
// 'terminal': terminalkey.terminal,
// 'tools': terminalkey.tools,
// 'travel': terminalkey.travel,
// 'video': terminalkey.video,
// 'word': terminalkey.word,
// 'xfer': terminalkey.xfer,
  'ZoomIn': TerminalKey.zoomIn,
  'ZoomOut': TerminalKey.zoomOut,
// 'away': terminalkey.away,
// 'messenger': terminalkey.messenger,
// 'webcam': terminalkey.webcam,
// 'mailforward': terminalkey.mailforward,
// 'pictures': terminalkey.pictures,
// 'music': terminalkey.music,
// 'battery': terminalkey.battery,
// 'bluetooth': terminalkey.bluetooth,
// 'wlan': terminalkey.wlan,
// 'uwb': terminalkey.uwb,
// 'audioforward': terminalkey.audioforward,
// 'audiorepeat': terminalkey.audiorepeat,
// 'audiorandomplay': terminalkey.audiorandomplay,
// 'subtitle': terminalkey.subtitle,
// 'audiocycletrack': terminalkey.audiocycletrack,
// 'time': terminalkey.time,
// 'hibernate': terminalkey.hibernate,
// 'view': terminalkey.view,
// 'topmenu': terminalkey.topmenu,
// 'powerdown': terminalkey.powerdown,
// 'suspend': terminalkey.suspend,
// 'contrastadjust': terminalkey.contrastadjust,
// 'touchpadtoggle': terminalkey.touchpadtoggle,
// 'touchpadon': terminalkey.touchpadon,
// 'touchpadoff': terminalkey.touchpadoff,
// 'micmute': terminalkey.micmute,
// 'red': terminalkey.red,
// 'green': terminalkey.green,
// 'yellow': terminalkey.yellow,
// 'blue': terminalkey.blue,
  'ChannelUp': TerminalKey.channelUp,
  'ChannelDown': TerminalKey.channelDown,
// 'guide': terminalkey.guide,
  'Info': TerminalKey.info,
// 'settings': terminalkey.settings,
// 'micvolumeup': terminalkey.micvolumeup,
// 'micvolumedown': terminalkey.micvolumedown,
// 'new': terminalkey.new,
  'Open': TerminalKey.open,
  'Find': TerminalKey.find,
  'Undo': TerminalKey.undo,
  'Redo': TerminalKey.redo,
  'MediaLast': TerminalKey.mediaLast,
// 'unknown': terminalkey.unknown,
// 'call': terminalkey.call,
// 'camera': terminalkey.camera,
// 'camerafocus': terminalkey.camerafocus,
// 'context1': terminalkey.context1,
// 'context2': terminalkey.context2,
// 'context3': terminalkey.context3,
// 'context4': terminalkey.context4,
// 'flip': terminalkey.flip,
// 'hangup': terminalkey.hangup,
// 'no': terminalkey.no,
  'Select': TerminalKey.select,
// 'yes': terminalkey.yes,
// 'togglecallhangup': terminalkey.togglecallhangup,
// 'voicedial': terminalkey.voicedial,
// 'lastnumberredial': terminalkey.lastnumberredial,
// 'execute': terminalkey.execute,
// 'printer': terminalkey.printer,
// 'play': terminalkey.play,
  'Sleep': TerminalKey.sleep,
// 'zoom': terminalkey.zoom,
  'Exit': TerminalKey.exit,
// 'cancel': terminalkey.cancel,
};
